SET BUILD_FOLDER=%~p0Build
SET ENGINE_FOLDER=%~p0Engine
SET GAME_FOLDER=%~p0Game
SET PROJECT_NAME=AssemblyGame

rd /S /q %BUILD_FOLDER%
mkdir %BUILD_FOLDER%

cd %ENGINE_FOLDER%
nasm -fwin32 %PROJECT_NAME%.asm -o %BUILD_FOLDER%\%PROJECT_NAME%.obj

cd %BUILD_FOLDER%
GoLink %PROJECT_NAME%.obj user32.dll kernel32.dll

%PROJECT_NAME%.exe