; Engine
global LoadEngine
export LoadEngine
global RunEngine
export RunEngine
global CleanupEngine
export CleanupEngine

; Memory
global MemoryAlloc
export MemoryAlloc
global MemoryFree
export MemoryFree

; Debug
global DebugValue
export DebugValue
global DebugPrintValue
export DebugPrintValue

global formatDecimal
export formatDecimal
global formatHex
export formatHex

; Graphics
global COLOR_BLACK
export COLOR_BLACK
global COLOR_WHITE
export COLOR_WHITE
global COLOR_RED
export COLOR_RED
global COLOR_GREEN
export COLOR_GREEN
global COLOR_BLUE
export COLOR_BLUE
global COLOR_CYAN
export COLOR_CYAN
global COLOR_MAGENTA
export COLOR_MAGENTA
global COLOR_YELLOW
export COLOR_YELLOW

global FillRectangle
export FillRectangle
global DrawString
export DrawString

; Input
global PRESS
export PRESS
global HOLD
export HOLD
global RELEASE
export RELEASE

global KEY_A
export KEY_A
global KEY_D
export KEY_D
global KEY_SPACE
export KEY_SPACE

global AddAction
export AddAction

; Linked List
global LL_Create
export LL_Create
global LL_Delete
export LL_Delete
global LL_Add
export LL_Add

; Time
global CalculateFPS
export CalculateFPS
global GetElapsed
export GetElapsed